name: Pull Request Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 25
      - name: Run unit tests
        run: ./gradlew test
